import '../parser/ast.dart';
import 'generator.dart';
import 'naming_strategy.dart';
import 'type_mappers.dart';
import 'type_visitor.dart';

/// Maximum string length for XDR strings (unlimited)
const xdrMaxStringLength = '~0';

/// Minimum value for formatting integers as hexadecimal in generated code.
/// Values >= 0x10000000 (268,435,456) are formatted as hex for readability,
/// as they typically represent RPC program numbers, which by convention use
/// the ranges 0x20000000-0x3fffffff (transient) or 0x00000000-0x1fffffff (registered).
const int _hexFormatThreshold = 0x10000000;

/// Maximum value for a 32-bit unsigned integer (0xFFFFFFFF = 4,294,967,295).
const int _maxUint32 = 0xFFFFFFFF;

/// C code generator for ONC-RPC specifications
///
/// Generates C code compatible with standard RPC libraries (rpc/rpc.h)
class CGenerator extends Generator {
  CGenerator(super.specification, super.config);

  final StringBuffer _headerBuffer = StringBuffer();
  final StringBuffer _sourceBuffer = StringBuffer();
  String _currentFile = '';

  @override
  NamingStrategy get naming => const CNamingStrategy();

  @override
  List<GeneratedArtifact> buildArtifacts() => [
        GeneratedArtifact(
          filename: '$basename.h',
          content: _headerBuffer.toString(),
          description: 'C header file',
        ),
        GeneratedArtifact(
          filename: '$basename.c',
          content: _sourceBuffer.toString(),
          description: 'C source file',
        ),
      ];

  @override
  void onStartSpecification(
    final Map<String, dynamic> config,
    final String name,
  ) {
    _currentFile = name;
    _writeHeaderPreamble();
    _writeSourcePreamble();
  }

  void _writeHeaderPreamble() {
    final baseName =
        _currentFile.replaceAll(RegExp(r'\.[^.]+$'), '').toUpperCase();
    final guard = '_${baseName}_H_RPCGEN';
    _headerBuffer.writeln('''
/*
 * Please do not edit this file.
 * It was generated using c_generator.
 */

#ifndef $guard
#define $guard

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif
''');
  }

  void _writeSourcePreamble() {
    final baseName = _currentFile.replaceAll(RegExp(r'\.[^.]+$'), '');
    _sourceBuffer.writeln('''
/*
 * Please do not edit this file.
 * It was generated using c_generator.
 */

#include "$baseName.h"
''');
  }

  @override
  void onEndSpecification(
    final Map<String, dynamic> config,
    final String name,
  ) {
    final baseName =
        _currentFile.replaceAll(RegExp(r'\.[^.]+$'), '').toUpperCase();
    final guard = '_${baseName}_H_RPCGEN';
    _headerBuffer.writeln('''

#ifdef __cplusplus
}
#endif

#endif /* !$guard */
''');
  }

  @override
  void onConstant(
    final Map<String, dynamic> config,
    final Constant<Value> constant,
  ) {
    // If header is empty, write preamble
    if (_headerBuffer.isEmpty) {
      _writeHeaderPreamble();
      _writeSourcePreamble();
    }

    // Format hex constants properly
    final value = constant.value;
    final integer = value.asInt;
    final String formatted;

    if (integer != null &&
        integer >= _hexFormatThreshold &&
        integer <= _maxUint32) {
      formatted = '0x${integer.toRadixString(16).toUpperCase()}';
    } else if (value.asReference != null) {
      formatted = value.asReference!;
    } else {
      formatted = value.toString();
    }

    _headerBuffer.writeln('#define ${constant.name} $formatted');
  }

  @override
  void onTypeDefinition(
    final Map<String, dynamic> config,
    final TypeDefinition definition,
  ) {
    if (definition is EnumTypeDefinition) {
      _generateEnum(definition);
    } else if (definition is StructTypeDefinition) {
      _generateStruct(definition);
    } else if (definition is UnionTypeDefinition) {
      _generateUnion(definition);
    } else {
      _generateTypedef(definition);
    }
  }

  void _generateEnum(final EnumTypeDefinition definition) {
    final type = definition.type as EnumTypeSpecifier;

    _headerBuffer.writeln('enum ${definition.name} {');
    for (var i = 0; i < type.values.length; i++) {
      final member = type.values[i];
      // Always add trailing comma (rpcgen compatibility)
      _headerBuffer.writeln('  ${member.name} = ${member.value},');
    }
    _headerBuffer
      ..writeln('};')
      ..writeln('typedef enum ${definition.name} ${definition.name};');

    _generateXdrFunctions(definition.name, 'enum');
  }

  void _generateStruct(final StructTypeDefinition definition) {
    final type = definition.type as StructTypeSpecifier;

    _headerBuffer.writeln('struct ${definition.name} {');
    for (final field in type.fields) {
      _headerBuffer
          .writeln('  ${_getCType(field.type, field.name, field.dimensions)};');
    }
    _headerBuffer
      ..writeln('};')
      ..writeln('typedef struct ${definition.name} ${definition.name};');

    _generateXdrFunctions(definition.name, 'struct', type);
  }

  void _generateUnion(final UnionTypeDefinition definition) {
    final type = definition.type as UnionTypeSpecifier;

    _headerBuffer
      ..writeln('struct ${definition.name} {')
      ..writeln(
        '  ${_getCType(type.variable.type, type.variable.name, [])};',
      )
      ..writeln('  union {');

    for (final caseSpec in type.arms) {
      if (!inspector.isVoid(caseSpec.type.type)) {
        _headerBuffer.writeln(
          '    ${_getCType(caseSpec.type.type, caseSpec.type.name, caseSpec.type.dimensions)};',
        );
      }
    }

    if (type.otherwise != null && !inspector.isVoid(type.otherwise!.type)) {
      _headerBuffer.writeln(
        '    ${_getCType(type.otherwise!.type, "default_val", type.otherwise!.dimensions)};',
      );
    }

    _headerBuffer
      ..writeln('  } ${definition.name}_u;')
      ..writeln('};')
      ..writeln('typedef struct ${definition.name} ${definition.name};');

    _generateXdrFunctions(definition.name, 'union', type);
  }

  void _generateTypedef(final TypeDefinition definition) {
    // Special handling for variable-length opaque/bytes arrays
    if (definition.type is OpaqueTypeSpecifier &&
        definition.dimensions.isNotEmpty &&
        !definition.dimensions.first.isFixedLength) {
      // Generate struct for variable-length opaque
      _headerBuffer
        ..writeln('typedef struct {')
        ..writeln('  u_int ${definition.name}_len;')
        ..writeln('  char *${definition.name}_val;')
        ..writeln('} ${definition.name};');
      _generateXdrFunctions(definition.name, 'opaque_typedef', definition);
    } else {
      final cType =
          _getCType(definition.type, definition.name, definition.dimensions);
      _headerBuffer.writeln('typedef $cType;');

      // Generate XDR functions for complex typedefs
      if (definition.dimensions.isNotEmpty ||
          _needsXdrFunctions(definition.type)) {
        _generateXdrFunctions(definition.name, 'typedef', definition);
      }
    }
  }

  void _generateXdrFunctions(
    final String type,
    final String kind, [
    final dynamic specification,
  ]) {
    _headerBuffer.writeln('extern bool_t xdr_$type(XDR *, $type *);');
    _sourceBuffer.writeln('''
bool_t xdr_$type(XDR *xdrs, $type *objp)
{''');

    if (kind == 'enum') {
      _sourceBuffer.writeln('  return xdr_enum(xdrs, (enum_t *)objp);');
    } else if (kind == 'struct' && specification != null) {
      _generateStructXdr(specification as StructTypeSpecifier);
    } else if (kind == 'union' && specification != null) {
      _generateUnionXdr(specification as UnionTypeSpecifier, type);
    } else if (kind == 'opaque_typedef' && specification != null) {
      final typeDef = specification as TypeDefinition;
      final maxSize = typeDef.dimensions.first.size.asInt ??
          typeDef.dimensions.first.size.asReference ??
          '~0';
      _sourceBuffer.writeln(
        '  return xdr_bytes(xdrs, (char **)&objp->${type}_val, (u_int *)&objp->${type}_len, $maxSize);',
      );
    } else if (kind == 'typedef' && specification != null) {
      _generateTypedefXdr(specification as TypeDefinition);
    }

    _sourceBuffer
      ..writeln('}')
      ..writeln();
  }

  void _generateStructXdr(final StructTypeSpecifier specification) {
    for (final field in specification.fields) {
      _sourceBuffer.write('  if (!');
      _generateFieldXdr(field);
      _sourceBuffer
        ..writeln(')')
        ..writeln('    return FALSE;');
    }
    _sourceBuffer.writeln('  return TRUE;');
  }

  void _generateUnionXdr(
    final UnionTypeSpecifier specification,
    final String name,
  ) {
    final discriminant = specification.variable;
    _sourceBuffer
      ..writeln(
        '  if (!${_getXdrFunction(discriminant.type)}(xdrs, &objp->${discriminant.name}))',
      )
      ..writeln('    return FALSE;')
      ..writeln('  switch (objp->${discriminant.name}) {');

    for (final caseSpec in specification.arms) {
      for (final label in caseSpec.labels) {
        final labelValue = label.asInt ?? label.asReference;
        _sourceBuffer.writeln('  case $labelValue:');
      }
      if (!inspector.isVoid(caseSpec.type.type)) {
        _sourceBuffer.write('    if (!');
        _generateFieldXdr(caseSpec.type, 'objp->${name}_u.');
        _sourceBuffer
          ..writeln(')')
          ..writeln('      return FALSE;');
      }
      _sourceBuffer.writeln('    break;');
    }

    if (specification.otherwise != null) {
      _sourceBuffer.writeln('  default:');
      if (!inspector.isVoid(specification.otherwise!.type)) {
        _sourceBuffer.write('    if (!');
        _generateFieldXdr(specification.otherwise!, 'objp->${name}_u.');
        _sourceBuffer
          ..writeln(')')
          ..writeln('      return FALSE;');
      }
      _sourceBuffer.writeln('    break;');
    }

    _sourceBuffer
      ..writeln('  }')
      ..writeln('  return TRUE;');
  }

  void _generateTypedefXdr(final TypeDefinition definition) {
    // For simple typedefs, use the appropriate XDR function
    final function = _getXdrFunction(definition.type);
    if (definition.dimensions.isEmpty) {
      _sourceBuffer.writeln('  return $function(xdrs, objp);');
    } else {
      // Handle arrays
      _generateArrayXdr(definition.type, definition.dimensions, 'objp');
      _sourceBuffer.writeln('  return TRUE;');
    }
  }

  void _generateFieldXdr(
    final TypeDefinition field, [
    final String prefix = 'objp->',
  ]) {
    final fieldName = '$prefix${field.name}';

    // Handle pointer types (Point *optional_point)
    if (field.type is PointerTypeSpecifier) {
      final pointerType = field.type as PointerTypeSpecifier;
      final base = _getBaseCType(pointerType.type);
      final function = _getXdrFunction(pointerType.type);
      _sourceBuffer.write(
        'xdr_pointer(xdrs, (char **)&$fieldName, sizeof($base), (xdrproc_t)$function)',
      );
    }
    // Check for optional types (pointer with size 1)
    else if (field.dimensions.isNotEmpty &&
        field.dimensions.first.size.asInt == 1 &&
        !field.dimensions.first.isFixedLength &&
        field.type is UserDefinedTypeSpecifier) {
      final base = _getBaseCType(field.type);
      final function = _getXdrFunction(field.type);
      _sourceBuffer.write(
        'xdr_pointer(xdrs, (char **)&$fieldName, sizeof($base), (xdrproc_t)$function)',
      );
    }
    // Strings with max length are not arrays
    else if (field.type is StringTypeSpecifier && field.dimensions.isNotEmpty) {
      // String with max length - use the specified max or reference to constant
      final size = field.dimensions.first.size;
      final max = size.asInt?.toString() ?? size.asReference ?? '~0';
      _sourceBuffer.write('xdr_string(xdrs, &$fieldName, $max)');
    } else if (field.dimensions.isNotEmpty &&
        field.type is! StringTypeSpecifier) {
      _generateArrayXdr(field.type, field.dimensions, fieldName);
    } else if (field.type is StringTypeSpecifier) {
      _sourceBuffer.write('xdr_string(xdrs, &$fieldName, $xdrMaxStringLength)');
    } else if (field.type is OpaqueTypeSpecifier) {
      _sourceBuffer.write('xdr_opaque(xdrs, $fieldName, sizeof($fieldName))');
    } else {
      final function = _getXdrFunction(field.type);
      _sourceBuffer.write('$function(xdrs, &$fieldName)');
    }
  }

  void _generateArrayXdr(
    final TypeSpecifier type,
    final List<ArraySpecifier> dimensions,
    final String name,
  ) {
    final dim = dimensions.first;

    // Special handling for opaque arrays
    if (type is OpaqueTypeSpecifier) {
      if (dim.isFixedLength) {
        final size = dim.size.asInt ?? dim.size.asReference;
        _sourceBuffer.write('xdr_opaque(xdrs, $name, $size)');
      } else {
        final maxSize = dim.size.asInt ?? '~0';
        _sourceBuffer.write(
          'xdr_bytes(xdrs, (char **)&$name, (u_int *)&${name}_len, $maxSize)',
        );
      }
      return;
    }

    if (dim.isFixedLength) {
      final size = dim.size.asInt ?? dim.size.asReference;
      _sourceBuffer
        ..write('xdr_vector(xdrs, (char *)$name, $size, ')
        ..write('sizeof(${_getBaseCType(type)}), ')
        ..write('(xdrproc_t)${_getXdrFunction(type)})');
    } else {
      final maxSize = dim.size.asInt ?? '~0';
      _sourceBuffer
        ..write('xdr_array(xdrs, (char **)&$name, ')
        ..write('(u_int *)&${name}_len, $maxSize, ')
        ..write('sizeof(${_getBaseCType(type)}), ')
        ..write('(xdrproc_t)${_getXdrFunction(type)})');
    }
  }

  String _getCType(
    final TypeSpecifier type,
    final String name,
    final List<ArraySpecifier> dimensions,
  ) {
    final base = _getBaseCType(type);

    // Strings are already char* so don't add extra pointer for variable-length
    if (type is StringTypeSpecifier) {
      return '$base $name';
    }

    String declaration = base;

    // Handle pointers (optional types)
    if (type is UserDefinedTypeSpecifier &&
        dimensions.isNotEmpty &&
        dimensions.first.size.asInt == 1 &&
        !dimensions.first.isFixedLength) {
      return '$base *$name';
    }

    // Handle arrays
    if (dimensions.isNotEmpty) {
      declaration = '$base $name';
      for (final dim in dimensions) {
        if (dim.isFixedLength) {
          final size = dim.size.asInt ?? dim.size.asReference;
          declaration += '[$size]';
        } else {
          // Variable-length arrays become pointers
          declaration = '$base *$name';
          break;
        }
      }
    } else {
      declaration = '$base $name';
    }

    return declaration;
  }

  String _getBaseCType(final TypeSpecifier type) =>
      type.accept(const CTypeMapper());

  String _getXdrFunction(final TypeSpecifier type) =>
      type.accept(const CXdrFunctionMapper());

  bool _needsXdrFunctions(final TypeSpecifier type) =>
      type is! IntTypeSpecifier &&
      type is! FloatTypeSpecifier &&
      type is! DoubleTypeSpecifier &&
      type is! HyperTypeSpecifier;

  @override
  void onProgram(final Map<String, dynamic> config, final Program program) {
    // If header is empty, write preamble
    if (_headerBuffer.isEmpty) {
      _writeHeaderPreamble();
      _writeSourcePreamble();
    }

    _headerBuffer.writeln('/* Program: ${program.name} */');
    // Format hex constants properly
    final progValue = program.constant;
    final progHex = progValue >= _hexFormatThreshold
        ? '0x${progValue.toRadixString(16).toUpperCase()}'
        : progValue.toString();
    _headerBuffer.writeln('#define ${program.name} $progHex');

    for (final version in program.versions) {
      _headerBuffer.writeln('#define ${version.name} ${version.constant}');

      for (final procedure in version.procedures) {
        _headerBuffer
            .writeln('#define ${procedure.name} ${procedure.constant}');

        // Generate procedure prototype
        final returnType = _getBaseCType(procedure.type);
        String paramTypes = '';
        if (procedure.arguments.isNotEmpty) {
          paramTypes = procedure.arguments.map(_getBaseCType).join(', ');
        } else {
          paramTypes = 'void';
        }

        _headerBuffer
          ..writeln(
            'extern $returnType * ${procedure.name.toLowerCase()}_${version.constant}($paramTypes, CLIENT *);',
          )
          ..writeln(
            'extern $returnType * ${procedure.name.toLowerCase()}_${version.constant}_svc($paramTypes, struct svc_req *);',
          );
      }
    }
  }
}
